### ISSUE TITLE
pipelines frequently encounter unexpected SIGSTP on macOS

### ISSUE THREAD

**Issue by 39555** [reubeno/brush#151]
While using Brush I experience random 148 SIGSTP signals from child commands.

`brush --noprofile --norc`

<img width="157" alt="image" src="https://github.com/user-attachments/assets/33c97acb-b094-497a-8fba-c0b008d077c4">

<img width="499" alt="image" src="https://github.com/user-attachments/assets/6acb8100-d03d-4039-880a-e4f4f83db4e2">

**Comment by reubeno** [comment]
That's a good find, thanks for reporting it. Sounds like some kind of race condition given that it's not consistent. I wonder if it's fundamentally related to #58. The fact that you reproduced it with no asynchronous commands or piped commands is quite helpful to know.

**Comment by reubeno** [comment]
My quick attempts to reproduce the errors in the above screenshots weren't successful. @39555 -- just to confirm, which OS are you running on? (Is it Linux?)

**Comment by 39555** [comment]
I've tested on macOS M2 arm64, NixOS wsl x86_64 and Windows x86_64. And that problem seems to exist only on Mac

**Comment by reubeno** [comment]
@39555 -- thanks for the confirmation. That explains why I haven't seen it, as I do most of my testing on Linux (and infrequently on Windows). I've put some effort in the last few days to start running our existing test suites on macOS arm64 as part of GitHub PR checks. It will take some time to get them stable, I expect, but I'm anticipating that they will help catch basic issues like the one you've reported.

I'm also interested to know if the changes in #166 get us closer to resolving this issue. (I won't be surprised if they don't, but any fixes for this should be layered on those.)

**Comment by reubeno** [comment]
This ended up being a macOS-specific issue, and I believe fixed by #172. The signal-handling code had been hard-coding integer signal values rather than using appropriate, portable constants that are correctly defined for each supported platform. Fixing that improved the code and appears to have resolved the issue.

Thanks to the merged PR linked above, we now also run all tests on macOS as part of PR checks; that should help us keep a functional baseline for x86_64/Linux and arm64/macOS for now. Thanks again for reporting this, it's been good learning along the way.
